ERROR - 2023-11-11 10:59:08 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `users` ...', 0)
#1 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\OCR_Website\app\Services\LoginServices.php(129): CodeIgniter\Model->update('15', Array)
#8 C:\xampp\htdocs\OCR_Website\app\Controllers\User\LoginController.php(61): App\Services\LoginServices->hasResetInfo(Object(CodeIgniter\HTTP\IncomingRequest))
#9 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User\LoginController->validateReset()
#10 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User\LoginController))
#11 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\OCR_Website\public\index.php(81): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-11-11 10:59:08 --> Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `password` = :password:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Services\LoginServices.php(129): CodeIgniter\Model->update('15', [...])
 6 APPPATH\Controllers\User\LoginController.php(61): App\Services\LoginServices->hasResetInfo(Object(CodeIgniter\HTTP\IncomingRequest))
 7 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User\LoginController->validateReset()
 8 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\OCR_Website\\public\\index.php')
ERROR - 2023-11-11 11:07:25 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `users` ...', 0)
#1 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\OCR_Website\app\Services\LoginServices.php(129): CodeIgniter\Model->update('15', Array)
#8 C:\xampp\htdocs\OCR_Website\app\Controllers\User\LoginController.php(61): App\Services\LoginServices->hasResetInfo(Object(CodeIgniter\HTTP\IncomingRequest))
#9 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User\LoginController->validateReset()
#10 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User\LoginController))
#11 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\OCR_Website\public\index.php(81): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-11-11 11:07:25 --> Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `password` = :password:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Services\LoginServices.php(129): CodeIgniter\Model->update('15', [...])
 6 APPPATH\Controllers\User\LoginController.php(61): App\Services\LoginServices->hasResetInfo(Object(CodeIgniter\HTTP\IncomingRequest))
 7 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User\LoginController->validateReset()
 8 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\OCR_Website\\public\\index.php')
ERROR - 2023-11-11 11:12:46 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `users` ...', 0)
#1 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\OCR_Website\app\Services\LoginServices.php(127): CodeIgniter\Model->update('15', Array)
#8 C:\xampp\htdocs\OCR_Website\app\Controllers\User\LoginController.php(61): App\Services\LoginServices->hasResetInfo(Object(CodeIgniter\HTTP\IncomingRequest))
#9 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User\LoginController->validateReset()
#10 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User\LoginController))
#11 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\OCR_Website\public\index.php(81): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-11-11 11:12:46 --> Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `password` = :password:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Services\LoginServices.php(127): CodeIgniter\Model->update('15', [...])
 6 APPPATH\Controllers\User\LoginController.php(61): App\Services\LoginServices->hasResetInfo(Object(CodeIgniter\HTTP\IncomingRequest))
 7 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User\LoginController->validateReset()
 8 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\OCR_Website\\public\\index.php')
ERROR - 2023-11-11 11:13:04 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `users` ...', 0)
#1 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\OCR_Website\app\Services\LoginServices.php(127): CodeIgniter\Model->update('15', Array)
#8 C:\xampp\htdocs\OCR_Website\app\Controllers\User\LoginController.php(61): App\Services\LoginServices->hasResetInfo(Object(CodeIgniter\HTTP\IncomingRequest))
#9 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User\LoginController->validateReset()
#10 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User\LoginController))
#11 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\OCR_Website\public\index.php(81): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\OCR_Website\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-11-11 11:13:04 --> Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `password` = :password:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Services\LoginServices.php(127): CodeIgniter\Model->update('15', [...])
 6 APPPATH\Controllers\User\LoginController.php(61): App\Services\LoginServices->hasResetInfo(Object(CodeIgniter\HTTP\IncomingRequest))
 7 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User\LoginController->validateReset()
 8 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User\LoginController))
 9 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\OCR_Website\\public\\index.php')
INFO - 2023-11-11 11:24:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
